# build final image
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    curl \
    # postgresql-client \
    software-properties-common \
    nginx \
    && curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y \
    yarn \
    python3.11 \
    python3.11-venv \
    python3.11-dev \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 \
    && update-alternatives --set python3 /usr/bin/python3.11 \
    && apt-get clean

WORKDIR /app

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./api/ ./api/
RUN pip3 install --upgrade pip
RUN pip3 install -r /app/api/requirements.txt
RUN pip3 install gunicorn
RUN pip3 install playwright
RUN playwright install --with-deps

COPY ./socket-server/ ./socket-server/
RUN cd /app/socket-server && yarn install

COPY ./client/ ./client/
RUN cd /app/client && yarn install

EXPOSE 80